version: '3.8'

services:
  zookeeper-source:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - kafka-mirror-maker2_kafka-net
    ports:
      - "2181:2181"

  kafka-source:
    image: confluentinc/cp-kafka:7.5.3
    networks:
      - kafka-mirror-maker2_kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-source:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-source:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-target:
    image: confluentinc/cp-kafka:7.5.3
    networks:
      - kafka-mirror-maker2_kafka-net
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-target:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-source:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.5.3
    networks:
      - kafka-mirror-maker2_kafka-net
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-source:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.5.3
    networks:
      - kafka-mirror-maker2_kafka-net
    ports:
      - "9095:9095"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-source:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  mirror-maker:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - kafka-source
      - kafka-target
    command: >
      kafka-mirror-maker mm2.properties
    volumes:
      - ./mm2.properties:/etc/kafka/mm2.properties

networks:
  kafka-mirror-maker2_kafka-net:
    driver: bridge
